language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - LARAVEL_VERSION=5.0.*
  - LARAVEL_VERSION=5.1.*
  - LARAVEL_VERSION=5.2.*
  - LARAVEL_VERSION=5.3.*
  - LARAVEL_VERSION=5.4.*

matrix:
  exclude:
    - php: 7.0
      env: LARAVEL_VERSION=5.0.*
    - php: 7.1
      env: LARAVEL_VERSION=5.0.*

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer require --no-update "phpspec/phpspec:~3.0"
  - composer require --no-update "laravel/framework:${LARAVEL_VERSION}"

install:
  - composer update --prefer-stable --no-interaction --no-suggest

script:
  - ./bin/phpspec run
