language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  - LARAVEL_VERSION=5.0.*
  - LARAVEL_VERSION=5.1.*
  - LARAVEL_VERSION=5.2.*
  - LARAVEL_VERSION=5.3.*
  - LARAVEL_VERSION=5.4.*

before_install:
  - composer require --no-update "phpspec/phpspec:~3.0"
  - composer require --no-update "laravel/framework:${LARAVEL_VERSION}"

install:
  - composer update --prefer-source --no-interaction

script:
  - ./bin/phpspec run
